export const AGREGAR_UNA_CUENTA = 'AGREGAR_UNA_CUENTA';
export const OBTENER_TODAS_LAS_CUENTAS = 'OBTENER_TODAS_LAS_CUENTAS';
export const OBTENER_UNA_CUENTA = 'OBTENER_UNA_CUENTA';
export const OBTENER_UNA_CUENTA_DE_LA_DB = 'OBTENER_UNA_CUENTA_DE_LA_DB';
export const EDITAR_CUENTA = 'EDITAR_CUENTA';
export const ELIMINAR_UNA_CUENTA = 'ELIMINAR_UNA_CUENTA';